---

services:

  db-init:
    build:
      context: .
      tags:
        - "consartist/blog-spring-cacheable"
    platform: linux/amd64
    environment:
      SPRING_PROFILES_ACTIVE: "postgres,create-drop"
    depends_on:
      - db

  web:
    image: "consartist/blog-spring-cacheable"
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: "postgres,redis"
    deploy:
      mode: replicated
      replicas: 5
      endpoint_mode: dnsrr
    depends_on:
      - db-init

  cache:
    image: redis:latest
    expose:
      - "6379"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    command: -c 'shared_buffers=512MB' -c 'max_connections=400'
    expose:
      - "5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

