spring:
  cache:
    type: SIMPLE
  devtools:
    restart:
      # Disabled b/c I learned that Intellij will Hot Swap for me (which is faster than a spring restart).
      # Maybe I should just remove the devtools jar, but I'll leave it for now.
      enabled: false
    livereload:
      enabled: false
  h2:
    console.enabled: true
  jpa:
    properties:
      # https://stackoverflow.com/a/76137193
      hibernate.hbm2ddl.import_files_sql_extractor: "org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor"
