spring:
  mvc:
    servlet:
      load-on-startup: 1
  cache:
    type: SIMPLE
  devtools:
    restart:
      # Disabled b/c I learned that Intellij will Hot Swap for me (which is faster than a spring restart).
      # Maybe I should just remove the devtools jar, but I'll leave it for now.
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: "jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "app"
    password: "password"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties:
      # https://stackoverflow.com/a/76137193
      hibernate.hbm2ddl.import_files_sql_extractor: "org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor"
      hibernate.dialect: "org.hibernate.dialect.H2Dialect"

management:
  health:
    redis:
      enabled: false