---

services:

  db-init:
    extends:
      file: common-services.yaml
      service: app-builder
    environment:
      SPRING_PROFILES_ACTIVE: "postgres,create-drop"
    depends_on:
      db:
        condition: service_healthy

  web:
    extends:
      file: common-services.yaml
      service: replicated-app
    environment:
      SPRING_PROFILES_ACTIVE: "postgres,redis"
    depends_on:
      - db-init

  cache:
    extends:
      file: common-services.yaml
      service: redis

  proxy:
    extends:
      file: common-services.yaml
      service: nginx

  db:
    extends:
      file: common-services.yaml
      service: postgres

  adminer:
    extends:
      file: common-services.yaml
      service: adminer

