---

services:

  db-init:
    extends:
      file: common-services.yaml
      service: app-builder
    environment:
      SPRING_PROFILES_ACTIVE: "postgres,create-drop"
    depends_on:
      - db

  web:
    extends:
      file: common-services.yaml
      service: replicated-app
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
    depends_on:
      - db-init

  proxy:
    extends:
      file: common-services.yaml
      service: nginx

  db:
    extends:
      file: common-services.yaml
      service: postgres

  adminer:
    extends:
      file: common-services.yaml
      service: adminer

