---

services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      tags:
        - "consartist/blog-spring-cacheable"
    platform: linux/amd64
    ports:
      - "8080:8080"